name: Build project

on:
  push: { branches: [release] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL # WebGL.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      # Checkout Repo
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      # Cache
      - name: Load / Save Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      # Build
      - name: Build Game
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      # Upload Artifact
      - name: Upload Game as an Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      # Deploy (Windows)
      - name: Deploy Game to Itch (Windows)
        uses: josephbmanley/butler-publish-itchio-action@master
        if: ${{ matrix.targetPlatform == 'StandaloneWindows64'}}
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: visual-novel-continuous-integration-test
          ITCH_USER: sakyawira
          PACKAGE: build/${{ matrix.targetPlatform }}
      # Deploy (WebGL)
      - name: Deploy Game to Itch (WebGL)
        uses: josephbmanley/butler-publish-itchio-action@master
        if: ${{ matrix.targetPlatform == 'WebGL'}} 
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: HTML
          ITCH_GAME: visual-novel-continuous-integration-test
          ITCH_USER: sakyawira
          PACKAGE: build/${{ matrix.targetPlatform }}